CREATE TABLE IF NOT EXISTS log_duty_free_store_mtd_sales_import (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  file_name VARCHAR(255) NOT NULL COMMENT '源文件名',
  file_path VARCHAR(500) NULL COMMENT '源文件路径',
  file_md5 CHAR(32) NULL COMMENT '源文件MD5',
  source_sheet VARCHAR(100) NOT NULL DEFAULT '免税月累计' COMMENT '来源工作表',
  target_month DATE NULL COMMENT '目标月份首日',
  data_version VARCHAR(32) NULL COMMENT '数据版本',
  store_count INT NOT NULL DEFAULT 0 COMMENT '命中的门店数',
  records_total INT NOT NULL DEFAULT 0 COMMENT '源门店行数',
  records_inserted INT NOT NULL DEFAULT 0 COMMENT '实际写入行数',
  changed_store_count INT NOT NULL DEFAULT 0 COMMENT '变更门店数',
  new_store_count INT NOT NULL DEFAULT 0 COMMENT '新增门店数',
  exited_store_count INT NOT NULL DEFAULT 0 COMMENT '退出门店数',
  status VARCHAR(20) NOT NULL COMMENT '执行状态',
  message VARCHAR(1000) NULL COMMENT '执行摘要或错误信息',
  started_at DATETIME NULL COMMENT '开始时间',
  finished_at DATETIME NULL COMMENT '结束时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id),
  KEY idx_log_duty_free_store_mtd_sales_import_created_at (created_at),
  KEY idx_log_duty_free_store_mtd_sales_import_status (status),
  KEY idx_log_duty_free_store_mtd_sales_import_target_month (target_month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='免税门店外部月累计销售额导入日志表';