CREATE TABLE IF NOT EXISTS cfg_store_report_attr_snapshot (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  target_month DATE NOT NULL COMMENT '目标月份首日',
  target_version VARCHAR(32) NOT NULL DEFAULT 'v1' COMMENT '目标版本号',
  store_id BIGINT NOT NULL COMMENT '店仓ID(dim_store.store_id)',
  store_code VARCHAR(40) NOT NULL COMMENT '店仓编码(dim_store.store_code)',
  store_name VARCHAR(255) NOT NULL COMMENT '店仓名称(dim_store.store_name)',
  report_channel_type VARCHAR(20) NOT NULL COMMENT '日报渠道类型',
  report_channel_type_group VARCHAR(20) NOT NULL COMMENT '日报渠道粗分类',
  store_grade VARCHAR(20) NULL COMMENT '店铺等级',
  is_duty_free CHAR(1) NOT NULL DEFAULT 'N' COMMENT '是否免税(Y/N)',
  is_include_in_daily_report CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '是否纳入日报(Y/N)',
  remark VARCHAR(500) NULL COMMENT '业务备注',
  effective_start_date DATE NOT NULL COMMENT '本次同步生效开始日期',
  effective_end_date DATE NOT NULL DEFAULT '9999-12-31' COMMENT '本次同步默认生效结束日期',
  source_file_name VARCHAR(255) NULL COMMENT '来源文件名',
  source_file_md5 CHAR(32) NULL COMMENT '来源文件MD5',
  updated_by VARCHAR(64) NULL COMMENT '最近更新人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_cfg_store_report_attr_snapshot (target_month, target_version, store_id),
  KEY idx_cfg_store_report_attr_snapshot_lookup (target_month, target_version, report_channel_type),
  KEY idx_cfg_store_report_attr_snapshot_store (store_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门店日报业务属性当前快照表';