CREATE TABLE IF NOT EXISTS ads_dabo_order_label (
    source_file VARCHAR(255) NOT NULL COMMENT '来源 Excel 文件名',
    source_sheet VARCHAR(128) NOT NULL COMMENT '来源工作表',
    source_file_mtime DATETIME NOT NULL COMMENT '来源文件修改时间',
    first_source_row_number INT NOT NULL COMMENT '首个来源行号',
    source_row_count INT NOT NULL DEFAULT 0 COMMENT '同 system_order_id 命中的来源行数',
    system_order_id VARCHAR(512) NOT NULL COMMENT '原始系统单号',
    canonical_system_order_id VARCHAR(512) NULL COMMENT '归一后的优先桥接键',
    normalization_status VARCHAR(32) NOT NULL DEFAULT 'unreviewed' COMMENT '归一状态',
    normalization_rule VARCHAR(64) NULL COMMENT '归一规则名',
    normalization_evidence TEXT NULL COMMENT '归一证据 JSON',
    platform_order_id VARCHAR(128) NULL COMMENT '平台单号',
    is_dabo_order TINYINT NOT NULL DEFAULT 1 COMMENT '是否达播订单',
    dabo_source VARCHAR(64) NOT NULL DEFAULT 'yunque_order_management' COMMENT '标签来源',
    dabo_channel_code VARCHAR(32) NOT NULL COMMENT '达播渠道代码',
    dabo_channel_name VARCHAR(64) NOT NULL COMMENT '达播渠道名称',
    influencer_id VARCHAR(128) NULL COMMENT '主播ID',
    influencer_name VARCHAR(128) NOT NULL COMMENT '主播名称',
    order_status VARCHAR(64) NOT NULL COMMENT '订单状态',
    platform_ship_time VARCHAR(32) NULL COMMENT '平台发货时间原始文本',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (source_file, system_order_id),
    KEY idx_ads_dabo_order_label_system_order (system_order_id),
    KEY idx_ads_dabo_order_label_canonical_system_order (canonical_system_order_id(255)),
    KEY idx_ads_dabo_order_label_channel (dabo_channel_code),
    KEY idx_ads_dabo_order_label_file_mtime (source_file_mtime)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='达播订单标签表（统一 Excel 标签主线）';