CREATE TABLE IF NOT EXISTS cfg_store_assessment_subject_target_daily (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  target_date DATE NOT NULL COMMENT '目标日期',
  target_month DATE NOT NULL COMMENT '目标月份首日',
  subject_code VARCHAR(64) NOT NULL COMMENT '统计主体编码',
  subject_name VARCHAR(255) NOT NULL COMMENT '统计主体名称',
  assessment_mode VARCHAR(20) NOT NULL COMMENT '考核模式：独立/合并',
  month_target DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '月目标',
  day_target DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '日目标',
  target_version VARCHAR(32) NOT NULL DEFAULT 'v1' COMMENT '目标版本号',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_by VARCHAR(64) NULL COMMENT '创建人',
  updated_by VARCHAR(64) NULL COMMENT '更新人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_cfg_store_assessment_subject_target_daily (target_date, subject_code, target_version),
  KEY idx_cfg_store_assessment_subject_target_month (target_month, target_version),
  KEY idx_cfg_store_assessment_subject_target_subject (subject_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门店日报统计主体日目标表';


CREATE TABLE IF NOT EXISTS cfg_store_assessment_assignment (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  target_month DATE NOT NULL COMMENT '目标月份首日',
  target_version VARCHAR(32) NOT NULL DEFAULT 'v1' COMMENT '目标版本号',
  store_id BIGINT NOT NULL COMMENT '门店ID',
  store_code VARCHAR(40) NOT NULL COMMENT '门店编码',
  store_name VARCHAR(255) NOT NULL COMMENT '门店名称',
  subject_code VARCHAR(64) NOT NULL COMMENT '统计主体编码',
  assignment_role VARCHAR(20) NOT NULL COMMENT '归属角色：主店/快闪/独立',
  is_joint_assessment CHAR(1) NOT NULL DEFAULT 'N' COMMENT '是否共同考核（Y/N）',
  anchor_store_id BIGINT NULL COMMENT '挂靠主店ID',
  anchor_store_name VARCHAR(255) NULL COMMENT '挂靠主店名称',
  effective_start_date DATE NOT NULL COMMENT '生效开始日',
  effective_end_date DATE NOT NULL COMMENT '生效结束日',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_by VARCHAR(64) NULL COMMENT '创建人',
  updated_by VARCHAR(64) NULL COMMENT '更新人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_cfg_store_assessment_assignment (target_month, target_version, store_id, effective_start_date),
  KEY idx_cfg_store_assessment_assignment_lookup (target_month, target_version, effective_start_date, effective_end_date),
  KEY idx_cfg_store_assessment_assignment_subject (target_month, target_version, subject_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门店日报统计主体归属配置表';


CREATE TABLE IF NOT EXISTS ads_store_daily_subject_report (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  report_date DATE NOT NULL COMMENT '报告日期',
  subject_code VARCHAR(64) NOT NULL COMMENT '统计主体编码',
  subject_name VARCHAR(255) NOT NULL COMMENT '统计主体名称',
  subject_source VARCHAR(32) NOT NULL COMMENT '主体来源：default_independent/configured_subject',
  assessment_mode VARCHAR(20) NOT NULL COMMENT '考核模式：独立/合并',
  anchor_store_id BIGINT NULL COMMENT '挂靠主店ID',
  anchor_store_name VARCHAR(255) NULL COMMENT '挂靠主店名称',
  report_channel_type VARCHAR(32) NOT NULL DEFAULT '未配置' COMMENT '经营渠道细分类',
  member_store_count INT NOT NULL DEFAULT 0 COMMENT '主体内门店数',
  day_sales_amt DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '日销售额',
  day_sales_qty INT NOT NULL DEFAULT 0 COMMENT '日销量',
  day_order_cnt INT NOT NULL DEFAULT 0 COMMENT '日订单数',
  day_attach_rate DECIMAL(18,4) NULL COMMENT '日连带率',
  day_avg_ticket DECIMAL(18,2) NULL COMMENT '日客单价',
  day_target DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '日目标',
  day_ach_rate DECIMAL(18,4) NULL COMMENT '日达成率',
  mtd_sales_amt DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '月累计销售额',
  mtd_sales_qty INT NOT NULL DEFAULT 0 COMMENT '月累计销量',
  mtd_order_cnt INT NOT NULL DEFAULT 0 COMMENT '月累计订单数',
  mtd_attach_rate DECIMAL(18,4) NULL COMMENT '月累计连带率',
  mtd_avg_ticket DECIMAL(18,2) NULL COMMENT '月累计客单价',
  month_target DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '月目标',
  month_ach_rate DECIMAL(18,4) NULL COMMENT '月达成率',
  last_month_mtd_sales_amt DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '上月同期累计销售额',
  last_month_mtd_sales_qty INT NOT NULL DEFAULT 0 COMMENT '上月同期累计销量',
  last_year_mtd_sales_amt DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '去年同期累计销售额',
  yoy_rate DECIMAL(18,4) NULL COMMENT '销售额同比率',
  yoy_amt_diff DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '销售额同比差值',
  last_year_mtd_sales_qty INT NOT NULL DEFAULT 0 COMMENT '去年同期累计销量',
  yoy_qty_rate DECIMAL(18,4) NULL COMMENT '销量同比率',
  yoy_qty_diff INT NOT NULL DEFAULT 0 COMMENT '销量同比差值',
  day_rank INT NULL COMMENT '日销排名',
  mtd_rank INT NULL COMMENT '月销排名',
  time_progress DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '时间进度',
  data_version VARCHAR(32) NOT NULL DEFAULT 'v1' COMMENT '数据版本号',
  etl_time DATETIME NOT NULL COMMENT 'ETL时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_ads_store_daily_subject_report (report_date, subject_code, data_version),
  KEY idx_ads_store_daily_subject_report_code (subject_code),
  KEY idx_ads_store_daily_subject_report_rank (report_date, data_version, mtd_rank)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门店日报统计主体层宽表';